### ISSUE TITLE
Running the tool throws: At least one choice must be selectable

### ISSUE THREAD

**Issue by rdsedmundo** [campvanilla/ditto#6]
Tried first with `pnpm`, then went to try with `npm` and got the same error.

```sh
$ npx @campvanilla/ditto-cli                                                                                                                                                                  8s  16.15.0 11:53:40 AM
Need to install the following packages:
  @campvanilla/ditto-cli@1.1.2
Ok to proceed? (y) y
/Users/work/.npm/_npx/1c411290f289f2c0/node_modules/enquirer/lib/types/array.js:38
      throw new Error('At least one choice must be selectable');
            ^

Error: At least one choice must be selectable
    at AutoComplete.reset (/Users/work/.npm/_npx/1c411290f289f2c0/node_modules/enquirer/lib/types/array.js:38:13)
    at async AutoComplete.initialize (/Users/work/.npm/_npx/1c411290f289f2c0/node_modules/enquirer/lib/types/array.js:25:5)
    at async /Users/work/.npm/_npx/1c411290f289f2c0/node_modules/enquirer/lib/prompt.js:236:7

Node.js v18.13.0
```

**Comment by nailliK** [comment]
I'm receiving the same error.

**Comment by nailliK** [comment]
BUMP

Has this project been abandoned?

**Comment by rdsedmundo** [comment]
@abinavseelan @rheaditi
